/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista.Drive.archivos;

import com.controlador.Control_fuentes;

/**
 *
 * @author Juan Camilo
 */
public class panelConvert extends javax.swing.JPanel {

    /**
     * Creates new form panelConvert
     */
    public panelConvert() {
        initComponents();
    }
    
    public panelConvert(String imagen,String titulo) {
        initComponents();
        //Control_fuentes tf = new Control_fuentes("Ndes");
        //jLabel2.setFont(tf.MyFont(1, 28f));
        jLabel2.setText(titulo);
        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagen)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 64, 64));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 350, 30));
    }// </editor-fold>//GEN-END:initComponents

    public String getTitulo(){
        return jLabel2.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
