/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;


import com.controlador.Control_fuentes;
import com.controlador.busqueda;
import com.google.api.services.drive.model.File;
import com.vista.Drive.DriveFiles;
import com.vista.Drive.DriveTools;
import com.vista.Drive.autenticacion;
import com.vista.menu.MenuItems;
import com.vista.menu.MenuTools;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Juan Camilo
 */
public class Index extends javax.swing.JFrame {
    com.vista.Drive.DriveFiles Drivefiles;
    com.vista.Drive.DriveTools Drivetools;
    com.vista.menu.MenuTools MenuTool;
    com.vista.menu.MenuItems MenuItem;
    com.controlador.busqueda Oauth;
    Registro n;
    String panelAbierto = "";

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel11.setVisible(false);
        Control_fuentes cf = new Control_fuentes("texto");
        this.jLabel4.setFont(cf.MyFont(1, 20f));
        
        Control_fuentes df = new Control_fuentes("des");
        
        
        Control_fuentes tf = new Control_fuentes("titulo");
        this.jLabel2.setFont(tf.MyFont(1, 28f));
        
        
        String myString = "Este es el momento de manejar tu tiempo";
        String myString1 = "de manera eficiente.";
        jLabel5.setText(myString1);
        jLabel7.setText(myString);
        this.jLabel5.setFont(df.MyFont(1, 22f));
        this.jLabel7.setFont(df.MyFont(1, 22f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NombreUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        contraseñaUser = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        nameLBL4 = new javax.swing.JLabel();
        nameLBL6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        Drive = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameLBL2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameLBL1 = new javax.swing.JLabel();
        nameLBL5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nameLBL3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 244, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(25, 137, 172));
        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(151, 7, 71));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Organic Tools");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 120));

        NombreUser.setBackground(new java.awt.Color(254, 244, 232));
        NombreUser.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        NombreUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NombreUser.setText("Ingrese su nombre de usuario...");
        NombreUser.setToolTipText("");
        NombreUser.setBorder(null);
        NombreUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NombreUser.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        NombreUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Seleccion(evt);
            }
        });
        jPanel1.add(NombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 30));

        jSeparator1.setForeground(new java.awt.Color(230, 28, 93));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 120, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 240, 10));

        contraseñaUser.setBackground(new java.awt.Color(254, 244, 232));
        contraseñaUser.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        contraseñaUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contraseñaUser.setText("jPasswordField1");
        contraseñaUser.setBorder(null);
        contraseñaUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contraseñaUser.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        contraseñaUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                seleccionP(evt);
            }
        });
        jPanel1.add(contraseñaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 250, 30));

        jButton1.setBackground(new java.awt.Color(4, 222, 173));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/comprobado.png"))); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 120, 40));

        jLabel8.setBackground(new java.awt.Color(230, 28, 93));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 28, 93));
        jLabel8.setText("Registrate");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LlamarReg(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));
        jLabel8.getAccessibleContext().setAccessibleName("registro");

        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 230, 10));

        nameLBL4.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL4.setLabelFor(NombreUser);
        nameLBL4.setText("Contraseña:");
        jPanel1.add(nameLBL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        nameLBL6.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL6.setLabelFor(NombreUser);
        nameLBL6.setText("Nombre de usuario:");
        jPanel1.add(nameLBL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 474));

        jPanel2.setBackground(new java.awt.Color(254, 244, 232));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/calendar.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 130));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, 10));

        jLabel5.setText("b");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 360, 40));

        Drive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/conducir.png"))); // NOI18N
        Drive.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(Drive, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 110, 70));

        jLabel7.setText("a");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 360, 40));

        nameLBL2.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        nameLBL2.setLabelFor(NombreUser);
        nameLBL2.setText("Mantente conectado a");
        jPanel2.add(nameLBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Google drive");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 10, 200));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/enamorado.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 70, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/codificacion.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, 80));

        nameLBL1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL1.setLabelFor(NombreUser);
        nameLBL1.setText("Facíl de usar.");
        jPanel2.add(nameLBL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 200, -1));

        nameLBL5.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL5.setLabelFor(NombreUser);
        nameLBL5.setText("Sube y descarga archivos.");
        jPanel2.add(nameLBL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 556, 474));
        jPanel2.getAccessibleContext().setAccessibleName("jpanel2");

        jPanel3.setBackground(new java.awt.Color(0, 116, 228));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/zorrillo-en-cabeza-frontal.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        nameLBL3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        nameLBL3.setForeground(new java.awt.Color(255, 255, 255));
        nameLBL3.setText("Raccoon");
        jPanel3.add(nameLBL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 12, -1, -1));

        jLabel4.setBackground(new java.awt.Color(230, 28, 93));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("x");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarAplicacion(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 0, 40, 50));

        jLabel11.setBackground(new java.awt.Color(255, 204, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/flecha-izquierda.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11Volver(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 0, 40, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 846, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Seleccion(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Seleccion
        // TODO add your handling code here:
        NombreUser.selectAll();
    }//GEN-LAST:event_Seleccion

    private void seleccionP(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seleccionP
        // TODO add your handling code here:
        contraseñaUser.selectAll();
    }//GEN-LAST:event_seleccionP

    private void CerrarAplicacion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarAplicacion
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarAplicacion

    private void LlamarReg(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LlamarReg
        // TODO add your handling code here:
        Color ver = new Color(230,28,93);
        Color deat = new Color(64,75,105);
        if(jLabel8.getForeground().equals(ver)){
            this.jPanel2.setVisible(false);
            n = new Registro(this);
            getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 556, 474));
            jLabel8.setForeground(deat);
            jLabel11.setVisible(true);
            panelAbierto = "registro";
        }
    }//GEN-LAST:event_LlamarReg

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelAbierto = "menu";
        jLabel11.setVisible(true);
        this.set_panel_home(false);
        
        MenuTool = new MenuTools(this);
        getContentPane().add(MenuTool, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 474));
        
        MenuItem = new MenuItems(this);
        getContentPane().add(MenuItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 556, 474));
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void instancia_drive_tools(com.vista.Drive.DriveTools to){
        Drivetools = to;
    }
    
    public void instancia_drive_files(com.vista.Drive.DriveFiles fi){
        Drivefiles = fi;
    }
    
    public void instancia_drive_aut(com.controlador.busqueda aut){
        Oauth = aut;
    }
    
    public void set_posicion(String camino){
        panelAbierto = camino;
    }
    
    public void set_panel_home(boolean activa){
        jPanel1.setVisible(activa);
        jPanel2.setVisible(activa);
    }
    
    public void set_panel_menu(boolean activa){
        MenuItem.setVisible(activa);
        MenuTool.setVisible(activa);
    }
    
    private void destruye_panel_drive(){
        this.remove(Drivefiles);
        this.remove(Drivetools);
    }
    
    private void destruye_panel_menu(){
        this.remove(MenuItem);
        this.remove(MenuTool);
    }
    
    public void paso_informacion_drive(){
        List<File> descargar = Drivefiles.llama_archivos_seleccionados();
        if(!descargar.isEmpty()){
            Drivetools.recibir_informacion(descargar);
        }else{
            JOptionPane.showMessageDialog(this, "Debe de seleccionar archivos primero.", "Atención", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void jLabel11Volver(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11Volver
        // TODO add your handling code here:
        switch(panelAbierto){
            case "registro":
                n.setVisible(false);
                this.activaPanelHome();
                break;
            case "menu":
                destruye_panel_menu();
                this.set_panel_home(true);
                break;
            case "drive":
                destruye_panel_drive();
                this.set_panel_menu(true);
                break;
        }
    }//GEN-LAST:event_jLabel11Volver
    
    public void llamaDrive(String cod){
        List<File> archivos = new ArrayList<File>();
        try {
            archivos = Oauth.getNombreArc(cod);
            Drivefiles.RecibirArchivos(archivos);
        } catch (IOException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void activaPanelHome(){
        this.jPanel2.setVisible(true);
        Color ver = new Color(230,28,93);
        jLabel8.setForeground(ver);
        jLabel11.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(//"com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                                    //"javax.swing.plaf.metal.MetalLookAndFeel");
                                    "com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); //!!! Funciona solo para windows !!!
                                    //"com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");//!!! Funciona solo para windows !!!
                                    //"com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                                    //"com.sun.java.swing.plaf.gtk.GTKLookAndFeel");//!!! Funciona solo para Linux !!!
                                                
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al tratar de cambiar el LookAndFeel.\n\n" +
                "Se tomara el LookAndFeel por defecto.",
                "Error de paquete",
                JOptionPane.WARNING_MESSAGE);
                   
        }
            //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Drive;
    private javax.swing.JTextField NombreUser;
    private javax.swing.JPasswordField contraseñaUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel nameLBL1;
    private javax.swing.JLabel nameLBL2;
    private javax.swing.JLabel nameLBL3;
    private javax.swing.JLabel nameLBL4;
    private javax.swing.JLabel nameLBL5;
    private javax.swing.JLabel nameLBL6;
    // End of variables declaration//GEN-END:variables
}
