/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;


import com.controlador.Control_fuentes;
import com.controlador.LogicaUsuario;
import com.controlador.encriptador;
import com.google.api.services.drive.model.File;
import com.modelo.Organizador;
import com.modelo.Usuarios;
import com.vista.opciones.RespuestaModal;
import com.vista.menu.MenuItems;
import com.vista.menu.MenuTools;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Juan Camilo
 */
public class Index extends javax.swing.JFrame {
    com.vista.Drive.DriveFiles Drivefiles;
    com.vista.Drive.DriveTools Drivetools;
    
    com.vista.agenda.agendarTools AgendaTools;
    com.vista.agenda.agendarCalendar AgendaCalendar;
    
    com.vista.menu.MenuTools MenuTool;
    com.vista.menu.MenuItems MenuItem;
    com.controlador.busqueda Oauth;
    
    Registro panelRegistro;
    String panelAbierto = "";
    private boolean banderaUsuario;

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        this.setLocationRelativeTo(null);
        //
        jLabel11.setVisible(false);
        Control_fuentes cf = new Control_fuentes("texto");
        this.jLabel4.setFont(cf.MyFont(1, 20f));
        
        Control_fuentes df = new Control_fuentes("des");
        
        
        Control_fuentes tf = new Control_fuentes("titulo");
        this.jLabel2.setFont(tf.MyFont(1, 28f));
        
        
        String myString = "Este es el momento de manejar tu tiempo";
        String myString1 = "de manera eficiente.";
        jLabel5.setText(myString1);
        jLabel7.setText(myString);
        this.jLabel5.setFont(df.MyFont(1, 22f));
        this.jLabel7.setFont(df.MyFont(1, 22f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmailUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        contraseñaUser = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        nameLBL4 = new javax.swing.JLabel();
        nameLBL6 = new javax.swing.JLabel();
        panelNoticias = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        Drive = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameLBL2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameLBL1 = new javax.swing.JLabel();
        nameLBL5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nameLBL3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(25, 137, 172));
        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(151, 7, 71));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agendame");
        jLabel2.setToolTipText("");
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 210, 120));

        txtEmailUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        txtEmailUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmailUser.setText("Ingrese su correo electronico...");
        txtEmailUser.setToolTipText("");
        txtEmailUser.setBorder(null);
        txtEmailUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEmailUser.setSelectedTextColor(new java.awt.Color(0, 51, 255));
        txtEmailUser.setSelectionColor(new java.awt.Color(81, 173, 207));
        txtEmailUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Seleccion(evt);
            }
        });
        panelLogin.add(txtEmailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 30));

        jSeparator1.setForeground(new java.awt.Color(230, 28, 93));
        panelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 120, 10));
        panelLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 240, 10));

        contraseñaUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        contraseñaUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contraseñaUser.setText("jPasswordField1");
        contraseñaUser.setBorder(null);
        contraseñaUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contraseñaUser.setSelectedTextColor(new java.awt.Color(0, 51, 255));
        contraseñaUser.setSelectionColor(new java.awt.Color(81, 173, 207));
        contraseñaUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                seleccionP(evt);
            }
        });
        panelLogin.add(contraseñaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 250, 30));

        jButton1.setBackground(new java.awt.Color(4, 222, 173));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/comprobado.png"))); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelLogin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 120, 40));

        jLabel8.setBackground(new java.awt.Color(230, 28, 93));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 28, 93));
        jLabel8.setText("Registrate");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LlamarReg(evt);
            }
        });
        panelLogin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));
        jLabel8.getAccessibleContext().setAccessibleName("registro");

        panelLogin.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 230, 10));

        nameLBL4.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL4.setLabelFor(txtEmailUser);
        nameLBL4.setText("Contraseña:");
        panelLogin.add(nameLBL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        nameLBL6.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL6.setLabelFor(txtEmailUser);
        nameLBL6.setText("Correo Electronico:");
        panelLogin.add(nameLBL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        getContentPane().add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 474));

        panelNoticias.setBackground(new java.awt.Color(255, 255, 255));
        panelNoticias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelNoticias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/calendar.png"))); // NOI18N
        panelNoticias.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 130));
        panelNoticias.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 10));
        panelNoticias.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, 10));

        jLabel5.setText("b");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelNoticias.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 360, 40));

        Drive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/conducir.png"))); // NOI18N
        Drive.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelNoticias.add(Drive, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 110, 70));

        jLabel7.setText("a");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelNoticias.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 360, 40));

        nameLBL2.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        nameLBL2.setLabelFor(txtEmailUser);
        nameLBL2.setText("Mantente conectado a");
        panelNoticias.add(nameLBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Google drive");
        panelNoticias.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelNoticias.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 10, 200));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/enamorado.png"))); // NOI18N
        panelNoticias.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 70, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/codificacion.png"))); // NOI18N
        panelNoticias.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, 80));

        nameLBL1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL1.setLabelFor(txtEmailUser);
        nameLBL1.setText("Facíl de usar.");
        panelNoticias.add(nameLBL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 200, -1));

        nameLBL5.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL5.setLabelFor(txtEmailUser);
        nameLBL5.setText("Sube y descarga archivos.");
        panelNoticias.add(nameLBL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 200, -1));

        getContentPane().add(panelNoticias, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 556, 474));
        panelNoticias.getAccessibleContext().setAccessibleName("jpanel2");

        jPanel3.setBackground(new java.awt.Color(0, 116, 228));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/zorrillo-en-cabeza-frontal.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        nameLBL3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        nameLBL3.setForeground(new java.awt.Color(255, 255, 255));
        nameLBL3.setText("Raccoon");
        jPanel3.add(nameLBL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 12, -1, -1));

        jLabel4.setBackground(new java.awt.Color(230, 28, 93));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("x");
        jLabel4.setToolTipText("");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarAplicacion(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 0, 40, 50));

        jLabel11.setBackground(new java.awt.Color(255, 204, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/flecha-izquierda.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11Volver(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 0, 40, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 846, 50));
        jPanel3.getAccessibleContext().setAccessibleName("TaskBar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Seleccion(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Seleccion
        // TODO add your handling code here:
        txtEmailUser.selectAll();
    }//GEN-LAST:event_Seleccion

    private void seleccionP(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seleccionP
        // TODO add your handling code here:
        contraseñaUser.selectAll();
    }//GEN-LAST:event_seleccionP

    private void CerrarAplicacion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarAplicacion
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarAplicacion

    private void LlamarReg(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LlamarReg
        // TODO add your handling code here:
        Color ver = new Color(230,28,93);
        Color deat = new Color(64,75,105);
        if(jLabel8.getForeground().equals(ver)){
            this.panelNoticias.setVisible(false);
            panelRegistro = new Registro(this);
            panelRegistro.setBounds(290, 50, 556, 474);
            getContentPane().add(panelRegistro);
            jLabel8.setForeground(deat);
            jLabel11.setVisible(true);
            panelAbierto = "registro";
        }
    }//GEN-LAST:event_LlamarReg

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!txtEmailUser.getText().equals("superuser")){
            com.controlador.LogicaUsuario userDao = new LogicaUsuario();
            RespuestaModal response = new RespuestaModal(this, true);
            try{
                com.modelo.Usuarios user = userDao.BuscarUsuario(txtEmailUser.getText());
                com.controlador.encriptador md5 = new encriptador();

                if(user.getContraseña().equals(md5.getMD5(contraseñaUser.getText()))){
                    panelAbierto = "menu";
                    jLabel11.setVisible(true);
                    if(panelNoticias.isVisible()){
                        this.set_panel_home(false);
                    }else{
                        panelLogin.setVisible(false);
                        panelRegistro.setVisible(false); 
                        Color ver = new Color(230,28,93);
                        jLabel8.setForeground(ver);
                    }
                    
                    if(!user.getTipo())
                    {
                        banderaUsuario = true;
                        MenuTool = new MenuTools(this,user);
                        
                        getContentPane().add(MenuTool, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 474));

                        MenuItem = new MenuItems(this,user);
                        MenuItem.setBounds(290, 50, 556, 474);
                        getContentPane().add(MenuItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 556, 474) );
                    }else
                    {
                        this.setLayout(null);
                        banderaUsuario = false;
                        this.jPanel3.setBackground(Color.red);
                        jPanel3.setLayout(null);
                        jPanel3.setSize(450, 50);
                        
                        this.setSize(new Dimension(450,524));
                        jLabel11.setLocation(370, 0);
                        jLabel4.setLocation(410, 0);
                        
                        MenuItem = new MenuItems(this,user);
                        MenuItem.setBounds(0, 50, 450, 474);
                        MenuItem.setLayout(null);
                        JButton[] a = MenuItem.getBotonesM();
                        a[0].setBounds(0,205,450,80);
                        a[1].setBounds(0,110,450,80);
                        a[2].setBounds(0,15,450,80);
                        this.add(MenuItem);
                        
                        repaint();
                    }
                }else{
                    String texto = "<html><body>La contraseña es<br>incorrecta.<br></body></html>";
                   response.cargaDatos("¡Upps!", texto, "error");
                    response.setVisible(true);
                }
            }catch(Exception ex){
                System.out.println("error: " + ex.getMessage() + "\nemial: " + txtEmailUser.getText());
                String texto = "<html><body>No existe un usuario con<br>ese correo electronico.<br></body></html>";
                response.cargaDatos("¡Upps!", texto, "error");
                response.setVisible(true);
            }
        }else{
            panelAbierto = "menu";
            jLabel11.setVisible(true);
            if(panelNoticias.isVisible()){
                this.set_panel_home(false);
            }else{
                panelLogin.setVisible(false);
                panelRegistro.setVisible(false); 
            }

            Usuarios userDefault = new Usuarios();
            
            userDefault.setNombre("SuperUser");
            userDefault.setCorreo("abc@gmail.com");
            userDefault.setContraseña("1234");

            MenuTool = new MenuTools(this,userDefault);
            getContentPane().add(MenuTool, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 474));

            MenuItem = new MenuItems(this,userDefault);
            getContentPane().add(MenuItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 556, 474));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void instancia_drive_tools(com.vista.Drive.DriveTools to){
        Drivetools = to;
    }
    
    public void instancia_drive_files(com.vista.Drive.DriveFiles fi){
        Drivefiles = fi;
    }
    
    public void instancia_agenda_tools(com.vista.agenda.agendarTools to){
        AgendaTools = to;
    }
    
    public void instancia_agenda_calendar(com.vista.agenda.agendarCalendar ca){
        AgendaCalendar = ca;
    }
    
    public void instancia_drive_aut(com.controlador.busqueda aut){
        Oauth = aut;
    }
    
    public void set_posicion(String camino){
        panelAbierto = camino;
    }
    
    public void set_panel_home(boolean activa){
        panelLogin.setVisible(activa);
        panelNoticias.setVisible(activa);
    }
    
    public void set_panel_menu(boolean activa){
        MenuItem.setVisible(activa);
        MenuTool.setVisible(activa);
    }
    
    private void destruye_panel_drive(){
        this.remove(Drivefiles);
        this.remove(Drivetools);
    }
    
    private void destruye_panel_agenda(){
        this.remove(AgendaTools);
        this.remove(AgendaCalendar);
    }
    
    private void destruye_panel_menu(){
        this.remove(MenuItem);
        this.remove(MenuTool);
    }
    
    private void destruye_panel_menu_mayor(){
        this.remove(MenuItem);
    }
    
    public void paso_informacion_drive(){
        List<File> descargar = Drivefiles.llama_archivos_seleccionados();
        System.out.println("com.vista.Index.paso_informacion_drive()" + descargar.size());
        if(!descargar.isEmpty()){
            Drivetools.recibir_informacion(descargar);
        }else{
            JOptionPane.showMessageDialog(this, "Debe de seleccionar archivos primero.", "Atención", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void paso_informacion_agenda(){
        List<Organizador> datos = AgendaCalendar.llama_archivos_seleccionados_organizador();
        AgendaTools.recibir_informacion(datos);
    }
    
    private void jLabel11Volver(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11Volver
        // TODO add your handling code here:
        switch(panelAbierto){
            case "registro":
                panelRegistro.setVisible(false);
                this.activaPanelHome();
                break;
            case "menu":
                jLabel11.setVisible(false);
                if(banderaUsuario){
                    destruye_panel_menu();
                    this.set_panel_home(true);
                }else{
                    destruye_panel_menu_mayor();
                    reset();
                    this.set_panel_home(true);
                }
                break;
            case "drive":
                panelAbierto = "menu";
                destruye_panel_drive();
                this.set_panel_menu(true);
                break;
            case "organizador":
                panelAbierto = "menu";
                destruye_panel_agenda();
                this.set_panel_menu(true);
                break;
        }
    }//GEN-LAST:event_jLabel11Volver
    
    public void llamaDrive(String cod){
        List<File> archivos = new ArrayList<File>();
        try {
            archivos = Oauth.getNombreArc(cod);
            Drivefiles.RecibirArchivos(archivos);
        } catch (IOException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void activarOpcionesAgenda(boolean accion){
        AgendaTools.activaOpciones(accion);
    }
    
    public void actualizaAgenda(){
        AgendaCalendar.Actualizar();
    }
    
    public void desactualizaAgenda(){
        AgendaCalendar.desActualizar();
    }
    
    public void activaPanelHome(){
        this.panelNoticias.setVisible(true);
        Color ver = new Color(230,28,93);
        jLabel8.setForeground(ver);
        jLabel11.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
        UIManager.setLookAndFeel(//"com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                                    //"javax.swing.plaf.metal.MetalLookAndFeel");
                                    "com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); //!!! Funciona solo para windows !!!
                                    //"com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");//!!! Funciona solo para windows !!!
                                    //"com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                                    //"com.sun.java.swing.plaf.gtk.GTKLookAndFeel");//!!! Funciona solo para Linux !!!
                                                
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al tratar de cambiar el LookAndFeel.\n\n" +
                "Se tomara el LookAndFeel por defecto.",
                "Error de paquete",
                JOptionPane.WARNING_MESSAGE);
                   
        }
            //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Drive;
    private javax.swing.JPasswordField contraseñaUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel nameLBL1;
    private javax.swing.JLabel nameLBL2;
    private javax.swing.JLabel nameLBL3;
    private javax.swing.JLabel nameLBL4;
    private javax.swing.JLabel nameLBL5;
    private javax.swing.JLabel nameLBL6;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelNoticias;
    private javax.swing.JTextField txtEmailUser;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        this.setSize(new Dimension(846,524));
        this.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        this.jPanel3.setBackground(new Color(0,116,228));
        jPanel3.setSize(846, 50);
        jLabel4.setLocation(805, 0);
        jLabel11.setLocation(765, 0);
        
    }
}
