/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;

import com.controlador.Control_fuentes;

/**
 *
 * @author Juan Camilo
 */
public class Registro extends javax.swing.JPanel {
    Index vista;
    /**
     * Creates new form Registro
     * @param view
     */
    public Registro(Index view) {
        vista = view;
        initComponents();
        Control_fuentes df = new Control_fuentes("des");
        jLabel1.setFont(df.MyFont(1, 24f));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombreUser1 = new javax.swing.JTextField();
        NombreUser2 = new javax.swing.JTextField();
        nameLBL3 = new javax.swing.JLabel();
        nameLBL4 = new javax.swing.JLabel();
        nameLBL5 = new javax.swing.JLabel();
        nameLBL6 = new javax.swing.JLabel();
        contraseñaUser = new javax.swing.JPasswordField();
        contraseñaUser1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 244, 232));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setMinimumSize(new java.awt.Dimension(480, 410));
        setPreferredSize(new java.awt.Dimension(480, 428));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(151, 7, 71));
        jLabel1.setText("Registro_");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        NombreUser1.setBackground(new java.awt.Color(204, 204, 204));
        NombreUser1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        NombreUser1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NombreUser1.setText("Ingrese su nombre de usuario...");
        NombreUser1.setToolTipText("");
        NombreUser1.setBorder(null);
        NombreUser1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NombreUser1.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        NombreUser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreUser1Seleccion(evt);
            }
        });
        add(NombreUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 270, 30));

        NombreUser2.setBackground(new java.awt.Color(204, 204, 204));
        NombreUser2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        NombreUser2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NombreUser2.setText("Ingrese su correo electronico...");
        NombreUser2.setToolTipText("");
        NombreUser2.setBorder(null);
        NombreUser2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NombreUser2.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        NombreUser2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreUser2Seleccion(evt);
            }
        });
        add(NombreUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 270, 30));

        nameLBL3.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL3.setText("Contraseña");
        add(nameLBL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        nameLBL4.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL4.setText("Nombre de usuario:");
        add(nameLBL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        nameLBL5.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL5.setText("Email");
        add(nameLBL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        nameLBL6.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        nameLBL6.setText("Repite la contraseña");
        add(nameLBL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        contraseñaUser.setBackground(new java.awt.Color(204, 204, 204));
        contraseñaUser.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        contraseñaUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contraseñaUser.setText("jPasswordField1");
        contraseñaUser.setBorder(null);
        contraseñaUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contraseñaUser.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        contraseñaUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseñaUserseleccionP(evt);
            }
        });
        add(contraseñaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 270, 30));

        contraseñaUser1.setBackground(new java.awt.Color(204, 204, 204));
        contraseñaUser1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        contraseñaUser1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contraseñaUser1.setText("jPasswordField1");
        contraseñaUser1.setBorder(null);
        contraseñaUser1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contraseñaUser1.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        contraseñaUser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseñaUser1seleccionP(evt);
            }
        });
        add(contraseñaUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 270, 30));

        jButton1.setBackground(new java.awt.Color(4, 222, 173));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/comprobado.png"))); // NOI18N
        jButton1.setText("Listo");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cohete.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 150, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void NombreUser1Seleccion(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreUser1Seleccion
        // TODO add your handling code here:
        NombreUser1.selectAll();
    }//GEN-LAST:event_NombreUser1Seleccion

    private void NombreUser2Seleccion(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreUser2Seleccion
        // TODO add your handling code here:
        NombreUser2.selectAll();
    }//GEN-LAST:event_NombreUser2Seleccion

    private void contraseñaUserseleccionP(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseñaUserseleccionP
        // TODO add your handling code here:
        contraseñaUser.selectAll();
    }//GEN-LAST:event_contraseñaUserseleccionP

    private void contraseñaUser1seleccionP(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseñaUser1seleccionP
        // TODO add your handling code here:
        contraseñaUser1.selectAll();
    }//GEN-LAST:event_contraseñaUser1seleccionP


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NombreUser1;
    private javax.swing.JTextField NombreUser2;
    private javax.swing.JPasswordField contraseñaUser;
    private javax.swing.JPasswordField contraseñaUser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nameLBL3;
    private javax.swing.JLabel nameLBL4;
    private javax.swing.JLabel nameLBL5;
    private javax.swing.JLabel nameLBL6;
    // End of variables declaration//GEN-END:variables
}
