/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista.agenda.crearEntrada;

import com.controlador.Control_fuentes;
import com.controlador.LogicaOrganizador;
import com.modelo.Organizador;
import com.modelo.Usuarios;
import com.vista.Index;
import com.vista.opciones.RespuestaModal;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static javax.swing.UIManager.setLookAndFeel;

/**
 *
 * @author Juan Camilo
 */
public class CrearEntrada extends javax.swing.JFrame {
    private Index vista;
    Usuarios userAccedido;
    private String titulo;
    private String descripcion;
    private Date fecha;
    private int idO;
    private String tag;
    private int id;
    private String[] seleccion = {"Urgente","Importante","Normal","Baja"};
    LogicaOrganizador organizadorDAO = new LogicaOrganizador();
    private boolean activador = false;
    /**
     * Creates new form CrearEntrada
     */
    public CrearEntrada() {
        initComponents();
    }

    public CrearEntrada(Index vista, Usuarios userAccedido, ArrayList<Organizador> citasFiltradas) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void setActivador(boolean a){
        activador = a;
    }
    
    public CrearEntrada(Index view,Usuarios user) {
        initComponents();
        this.setLocationRelativeTo(null);
        vista = view;
        userAccedido = user;
        Control_fuentes cf = new Control_fuentes("texto");
        this.jLabel4.setFont(cf.MyFont(1, 20f));
        nameLBL8.setVisible(false);
    }
    
    public CrearEntrada(Index view,Usuarios user,String Titulo,String Descripcion, Date fecha,String Tag,int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        vista = view;
        userAccedido = user;
        Control_fuentes cf = new Control_fuentes("texto");
        this.jLabel4.setFont(cf.MyFont(1, 20f));
        nameLBL8.setVisible(false);
        lblTittle.setText(Titulo);
        lblDesp.setText(Descripcion);
        idO = id;
        slcFecha.setSelectedDate(toCalendar(fecha));
        int sel = 0;
        for (int i = 0; i < seleccion.length; i++) {
            if(seleccion[i].equals(Tag)){
                sel = i;
            }
        }
        comboTag.setSelectedIndex(sel);
        jButton1.setText("Actualizar");
    }

    public  Calendar toCalendar(Date date){ 
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        return cal;
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nameLBL3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTittle = new javax.swing.JTextField();
        nameLBL4 = new javax.swing.JLabel();
        slcFecha = new datechooser.beans.DateChooserPanel();
        nameLBL5 = new javax.swing.JLabel();
        nameLBL6 = new javax.swing.JLabel();
        nameLBL7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDesp = new javax.swing.JTextArea();
        comboTag = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        nameLBL8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 116, 228));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/zorrillo-en-cabeza-frontal.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        nameLBL3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        nameLBL3.setForeground(new java.awt.Color(255, 255, 255));
        nameLBL3.setText("Raccoon");
        jPanel3.add(nameLBL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 12, -1, -1));

        jLabel4.setBackground(new java.awt.Color(230, 28, 93));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("x");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4CerrarAplicacion(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 40, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTittle.setBackground(new java.awt.Color(204, 204, 204));
        lblTittle.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lblTittle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lblTittle.setText("Ingrese su nombre...");
        lblTittle.setToolTipText("");
        lblTittle.setBorder(null);
        lblTittle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTittle.setSelectedTextColor(new java.awt.Color(0, 51, 255));
        lblTittle.setSelectionColor(new java.awt.Color(81, 173, 207));
        lblTittle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblTittleSeleccion(evt);
            }
        });
        jPanel1.add(lblTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 350, 30));

        nameLBL4.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        nameLBL4.setText("Descripción");
        jPanel1.add(nameLBL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        slcFecha.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    slcFecha.setNavigateFont(new java.awt.Font("Yu Gothic UI Light", java.awt.Font.PLAIN, 14));
    slcFecha.setShowOneMonth(true);
    jPanel1.add(slcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 350, 170));

    nameLBL5.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
    nameLBL5.setText("Titulo de entrada");
    jPanel1.add(nameLBL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

    nameLBL6.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
    nameLBL6.setText("Selecciona la fecha de la entrada");
    jPanel1.add(nameLBL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

    nameLBL7.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
    nameLBL7.setText("Importancia");
    jPanel1.add(nameLBL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

    lblDesp.setBackground(new java.awt.Color(204, 204, 204));
    lblDesp.setColumns(20);
    lblDesp.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
    lblDesp.setLineWrap(true);
    lblDesp.setRows(5);
    lblDesp.setBorder(null);
    lblDesp.setOpaque(false);
    jScrollPane1.setViewportView(lblDesp);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 350, 80));

    comboTag.setBackground(new java.awt.Color(204, 204, 204));
    comboTag.setEditable(true);
    comboTag.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
    comboTag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgente", "Importante", "Normal", "Baja" }));
    comboTag.setSelectedIndex(2);
    comboTag.setBorder(null);
    comboTag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jPanel1.add(comboTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 310, -1));

    jButton1.setBackground(new java.awt.Color(4, 222, 173));
    jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/comprobado.png"))); // NOI18N
    jButton1.setText("Crear");
    jButton1.setBorder(null);
    jButton1.setBorderPainted(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 120, 40));

    nameLBL8.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
    nameLBL8.setForeground(new java.awt.Color(255, 51, 51));
    nameLBL8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    nameLBL8.setText("Registro exitoso");
    jPanel1.add(nameLBL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 170, 30));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 390, 560));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4CerrarAplicacion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4CerrarAplicacion
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel4CerrarAplicacion

    private void lblTittleSeleccion(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblTittleSeleccion
        // TODO add your handling code here:
        lblTittle.selectAll();
    }//GEN-LAST:event_lblTittleSeleccion

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jButton1.getText().equals("Crear")){
            try {
                // TODO add your handling code here:

                titulo = lblTittle.getText();
                if(!(titulo.equals("Ingrese su nombre...") || titulo.equals("") )){
                    descripcion = lblDesp.getText();
                    fecha = slcFecha.getSelectedDate().getTime();
                    tag = (String) comboTag.getSelectedItem();

                    List<Organizador> org = organizadorDAO.consultarCitas();
                    if(org.size() > 0){
                        int i,j;
                        int max = org.get(0).getIdorganizador();
                        for(i = 0; i < org.size(); i++)
                        {
                            if(max < org.get(i).getIdorganizador())
                            {
                                max = org.get(i).getIdorganizador();
                            }
                        }
                        id = max+1;
                    }else{
                        id = 1;
                    }

                    Organizador nuevaCita = new Organizador();

                    nuevaCita.setIdorganizador(id);
                    nuevaCita.setTitulo(titulo);
                    nuevaCita.setDescripcion(descripcion);
                    nuevaCita.setFecha(fecha);
                    nuevaCita.setTag(tag);
                    nuevaCita.setUsuariosCorreo(userAccedido);

                    organizadorDAO.registrarCita(nuevaCita);
                    RespuestaModal response = new RespuestaModal(this, true);
                    String texto = "<html><body>Se creo la cita<br>con exito.<br></body></html>";
                    response.cargaDatos("¡Exito!",texto, "exito");
                    response.setVisible(true);
                    nameLBL8.setVisible(false);
                    if(activador){
                        vista.actualizaAgenda();
                    }

                    this.dispose();
                }else{
                    RespuestaModal response = new RespuestaModal(this, true);
                    String texto = "<html><body>La cita debe contar con<br>un nombre valido.<br></body></html>";
                    response.cargaDatos("¡Upps!",texto, "error");
                    response.setVisible(true);
                }
            } catch (Exception ex) {
                Logger.getLogger(CrearEntrada.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            titulo = lblTittle.getText();
            descripcion = lblDesp.getText();
            fecha = slcFecha.getSelectedDate().getTime();
            tag = (String) comboTag.getSelectedItem();
            
            Organizador nuevaCita = new Organizador();

            nuevaCita.setIdorganizador(idO);
            nuevaCita.setTitulo(titulo);
            nuevaCita.setDescripcion(descripcion);
            nuevaCita.setFecha(fecha);
            nuevaCita.setTag(tag);
            nuevaCita.setUsuariosCorreo(userAccedido);

            organizadorDAO.modificarCita(nuevaCita);
            RespuestaModal response = new RespuestaModal(this, true);
                response.cargaDatos("¡Exito!", "Se actualizo la cita con\n"
                        + "exito.", "exito");
            response.setVisible(true);
            nameLBL8.setVisible(false);
            vista.actualizaAgenda();
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel"); 
            //UIManager.setLookAndFeel(//"com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                                    //"javax.swing.plaf.metal.MetalLookAndFeel");
                                    //"com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); //!!! Funciona solo para windows !!!
                                    //"com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");//!!! Funciona solo para windows !!!
                                    //"com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                                    //"com.sun.java.swing.plaf.gtk.GTKLookAndFeel");//!!! Funciona solo para Linux !!!
                                                
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al tratar de cambiar el LookAndFeel.\n\n" +
                "Se tomara el LookAndFeel por defecto.",
                "Error de paquete",
                JOptionPane.WARNING_MESSAGE);
                   
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTag;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblDesp;
    private javax.swing.JTextField lblTittle;
    private javax.swing.JLabel nameLBL3;
    private javax.swing.JLabel nameLBL4;
    private javax.swing.JLabel nameLBL5;
    private javax.swing.JLabel nameLBL6;
    private javax.swing.JLabel nameLBL7;
    private javax.swing.JLabel nameLBL8;
    private datechooser.beans.DateChooserPanel slcFecha;
    // End of variables declaration//GEN-END:variables
}
