/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista.agenda.panelesDias;

/**
 *
 * @author Juan Camilo
 */
public class panelDias extends javax.swing.JPanel {

    /**
     * Creates new form panelDias
     */
    public panelDias(String dia) {
        initComponents();
        lblDia.setText(dia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDia = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDia.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblDia.setText("jLabel1");
        add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        lblDia.getAccessibleContext().setAccessibleName("dia");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDia;
    // End of variables declaration//GEN-END:variables
}
