/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista.Drive;

import com.controlador.controlPaneles;
import com.google.api.services.drive.model.File;
import com.vista.Drive.archivos.FormatosArchivos;
import com.vista.Index;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author Juan Camilo
 */
public class DriveFiles extends javax.swing.JPanel {
    public com.vista.Index vista;
    public List<com.vista.Drive.archivos.FormatosArchivos> representacionA;
    public List<File> archivos;
    com.controlador.controlPaneles com;
    public String accion = "normal";
    List<File> encontrado;
    /**
     * Creates new form DriveFiles
     */
    public DriveFiles(Index view) {
        vista = view;
        initComponents();
        archivos = new ArrayList<>();
        btnBorraBusqueda.setVisible(false);
        nameLBL5.setVisible(false);
    }
    
    public void cambiaAespera(boolean actividad){
        nameLBL5.setVisible(!actividad);   
        nameLBL3.setVisible(actividad);
        btnBorraBusqueda.setEnabled(actividad);
        btnBusqueda.setEnabled(actividad);
    }
    
    public void RecibirArchivos( List<File> a){
        archivos = a;   
        crearPaneles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLBL3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        BusquedaArchivo = new javax.swing.JTextField();
        btnBorraBusqueda = new javax.swing.JButton();
        btnBusqueda = new javax.swing.JButton();
        nameLBL5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setMinimumSize(new java.awt.Dimension(480, 425));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLBL3.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        nameLBL3.setText("Tus archivos");
        add(nameLBL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 515, 340));

        BusquedaArchivo.setBackground(new java.awt.Color(204, 204, 204));
        BusquedaArchivo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BusquedaArchivo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BusquedaArchivo.setText("Ingrese nombre del archivo..");
        BusquedaArchivo.setToolTipText("");
        BusquedaArchivo.setBorder(null);
        BusquedaArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BusquedaArchivo.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        BusquedaArchivo.setSelectionColor(new java.awt.Color(81, 173, 207));
        BusquedaArchivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BusquedaArchivoSeleccion(evt);
            }
        });
        add(BusquedaArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 340, 30));

        btnBorraBusqueda.setBackground(new java.awt.Color(227, 97, 97));
        btnBorraBusqueda.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnBorraBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/flecha-retroceso.png"))); // NOI18N
        btnBorraBusqueda.setToolTipText("Borra la busqueda");
        btnBorraBusqueda.setBorder(null);
        btnBorraBusqueda.setBorderPainted(false);
        btnBorraBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorraBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorraBusquedaActionPerformed(evt);
            }
        });
        add(btnBorraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 55, 40, 40));

        btnBusqueda.setBackground(new java.awt.Color(123, 206, 204));
        btnBusqueda.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/buscar-lupa-simbolo-de-interfaz.png"))); // NOI18N
        btnBusqueda.setText("Buscar");
        btnBusqueda.setBorder(null);
        btnBusqueda.setBorderPainted(false);
        btnBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 55, 110, 40));

        nameLBL5.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        nameLBL5.setForeground(new java.awt.Color(255, 102, 102));
        nameLBL5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLBL5.setText("Espere por favor ...");
        add(nameLBL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 190, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BusquedaArchivoSeleccion(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BusquedaArchivoSeleccion
        // TODO add your handling code here:
        BusquedaArchivo.selectAll();
        
    }//GEN-LAST:event_BusquedaArchivoSeleccion

    private void btnBorraBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorraBusquedaActionPerformed
        // TODO add your handling code here:
        accion = "normal";
        crearPaneles();
        btnBorraBusqueda.setVisible(false);
    }//GEN-LAST:event_btnBorraBusquedaActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        // TODO add your handling code here:
        btnBorraBusqueda.setVisible(true);
        accion = "busca";
        encontrado = new ArrayList<>();
        for (int i = 0; i < archivos.size(); i++) {
            if(archivos.get(i).getTitle().contains(BusquedaArchivo.getText())){
                encontrado.add(archivos.get(i));
            }
        }
        
        crearPanelesDebusqueda(encontrado);
    }//GEN-LAST:event_btnBusquedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BusquedaArchivo;
    private javax.swing.JButton btnBorraBusqueda;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLBL3;
    private javax.swing.JLabel nameLBL5;
    // End of variables declaration//GEN-END:variables

    private void crearPaneles() {
        jPanel1.removeAll();
        representacionA = new ArrayList<>();
        int x = 10;
        int y = 10;
        int contador = 0;
        int wid = 148;
        int heig = 160;
        boolean tipo ;
        com = new controlPaneles(this);
        nameLBL3.setText("Tus archivos ("+archivos.size()+")");
        for (int i = 0; i < archivos.size(); i++) {
            if(contador == 3){
                y += heig + 10;  
                contador = 0;
                x = 10;
            }
            try{
                tipo = !archivos.get(i).getFileExtension().equals("null");
            }catch(java.lang.NullPointerException es){
                tipo = false;
            }
            
            com.vista.Drive.archivos.FormatosArchivos a = new FormatosArchivos(archivos.get(i).getTitle(), tipo);
            representacionA.add(a);
            
            a.setVisible(true);
            a.addMouseListener(com);
            jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, wid, heig));
            x += wid + 10;
            contador++;
        }
        
       
    }
    
    public List<File> llama_archivos_seleccionados(){
        List<Integer> a = com.DevolverSeleccion();
        List<File> seleccion = new ArrayList<>();
        seleccion.clear();
        for (int i = 0; i < a.size(); i++) {
            if(accion.equals("busca")){
                seleccion.add(encontrado.get(a.get(i)));
            }else{
                seleccion.add(archivos.get(a.get(i)));
            }
        }
        
        return seleccion;
    }

    private void crearPanelesDebusqueda(List<File> encontrado) {
        jPanel1.removeAll();
        representacionA = new ArrayList<>();
        int x = 10;
        int y = 10;
        int contador = 0;
        int wid = 148;
        int heig = 160;
        boolean tipo ;
        com = new controlPaneles(this);
        nameLBL3.setText("Archivos relacionados ("+encontrado.size()+")");
        for (int i = 0; i < encontrado.size(); i++) {
            if(contador == 3){
                y += heig + 10;  
                contador = 0;
                x = 10;
            }
            try{
                tipo = !encontrado.get(i).getFileExtension().equals("null");
            }catch(java.lang.NullPointerException es){
                tipo = false;
            }
            
            com.vista.Drive.archivos.FormatosArchivos a = new FormatosArchivos(encontrado.get(i).getTitle(), tipo);
            representacionA.add(a);
            
            a.setVisible(true);
            a.addMouseListener(com);
            jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, wid, heig));
            x += wid + 10;
            contador++;
        }
    }
}
