/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista.opciones;

import com.vista.menu.*;
import com.modelo.Usuarios;
import com.vista.Index;
import com.vista.agenda.crearEntrada.CrearEntrada;
import java.awt.Color;

/**
 *
 * @author Juan Camilo
 */
public class OpcionesTools extends javax.swing.JPanel {
    Index vista;
    Usuarios usuario;
    /**
     * Creates new form MenuTools
     */
    public OpcionesTools(Index view,Usuarios user) {
        initComponents();
        this.setName("MenuHerramientas");
        vista = view;
        usuario = user;
        nombreUsuario.setText(usuario.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLBL4 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        nameLBL6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(53, 92, 125));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLBL4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        nameLBL4.setForeground(new java.awt.Color(255, 255, 255));
        nameLBL4.setText("- Selección de fuente");
        add(nameLBL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        nombreUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/usuario.png"))); // NOI18N
        nombreUsuario.setText("User");
        nombreUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 30));

        jTextArea1.setBackground(new java.awt.Color(53, 92, 125));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 250, 120));

        nameLBL6.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        nameLBL6.setForeground(new java.awt.Color(255, 255, 255));
        nameLBL6.setText("- Opciones");
        add(nameLBL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nameLBL4;
    private javax.swing.JLabel nameLBL6;
    private javax.swing.JLabel nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
