/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista.agenda;

import com.vista.Index;
import java.awt.Color;

/**
 *
 * @author Juan Camilo
 */
public class agendarTools extends javax.swing.JPanel {
    Index vista;
    /**
     * Creates new form agendarTools
     */
    public agendarTools(Index view) {
        initComponents();
        vista = view;
        accesoR4.setVisible(false);
        accesoR2.setVisible(false);
    }
    
    public void activaOpciones(boolean accion){
        accesoR4.setVisible(accion);
        accesoR2.setVisible(accion);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Drive = new javax.swing.JLabel();
        accesoR2 = new javax.swing.JLabel();
        accesoR3 = new javax.swing.JLabel();
        accesoR4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(53, 92, 125));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Drive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/calendario.png"))); // NOI18N
        Drive.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(Drive, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 110, 90));

        accesoR2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        accesoR2.setForeground(new java.awt.Color(255, 255, 255));
        accesoR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/calendarioA.png"))); // NOI18N
        accesoR2.setText("Borrar cita");
        accesoR2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accesoR2cambio_paso(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accesoR2retorna_paso(evt);
            }
        });
        add(accesoR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, 30));

        accesoR3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        accesoR3.setForeground(new java.awt.Color(255, 255, 255));
        accesoR3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/calendarioA.png"))); // NOI18N
        accesoR3.setText("Crear nueva cita");
        accesoR3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accesoR3cambio_paso(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accesoR3retorna_paso(evt);
            }
        });
        add(accesoR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 230, 30));

        accesoR4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        accesoR4.setForeground(new java.awt.Color(255, 255, 255));
        accesoR4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/calendarioc.png"))); // NOI18N
        accesoR4.setText("Consultar cita");
        accesoR4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoR4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accesoR4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accesoR4MouseExited(evt);
            }
        });
        add(accesoR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void accesoR2cambio_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR2cambio_paso
        // TODO add your handling code here:
         Color n = new Color(95,204,156);
        accesoR2.setForeground(n);
    }//GEN-LAST:event_accesoR2cambio_paso

    private void accesoR2retorna_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR2retorna_paso
        // TODO add your handling code here:
        Color n = new Color(240,240,240);
        accesoR2.setForeground(n);
    }//GEN-LAST:event_accesoR2retorna_paso

    private void accesoR3cambio_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR3cambio_paso
        // TODO add your handling code here:
        Color n = new Color(95,204,156);
        accesoR3.setForeground(n);
    }//GEN-LAST:event_accesoR3cambio_paso

    private void accesoR3retorna_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR3retorna_paso

        Color n = new Color(240,240,240);
        accesoR3.setForeground(n);
    }//GEN-LAST:event_accesoR3retorna_paso

    private void accesoR4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR4MouseEntered
        // TODO add your handling code here:
        Color n = new Color(95,204,156);
        accesoR4.setForeground(n);
    }//GEN-LAST:event_accesoR4MouseEntered

    private void accesoR4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR4MouseExited
        // TODO add your handling code here:
        Color n = new Color(240,240,240);
        accesoR4.setForeground(n);
    }//GEN-LAST:event_accesoR4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Drive;
    private javax.swing.JLabel accesoR2;
    private javax.swing.JLabel accesoR3;
    private javax.swing.JLabel accesoR4;
    // End of variables declaration//GEN-END:variables
}
