/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista.agenda;

import com.modelo.Organizador;
import com.modelo.Usuarios;
import com.vista.Index;
import com.vista.agenda.crearEntrada.CrearEntrada;
import com.vista.opciones.DialogoConfirmacion;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author Juan Camilo
 */
public class agendarTools extends javax.swing.JPanel {
    Index vista;
    Usuarios userAccedido;
    List<Organizador> orga;
    /**
     * Creates new form agendarTools
     */
    public agendarTools(Index view, Usuarios user) {
        initComponents();
        this.setName("AgendaHerramientas");
        vista = view;
        userAccedido = user;
        accesoR4.setVisible(false);
        accesoR2.setVisible(false);
    }
    
    public void activaOpciones(boolean accion){
        accesoR4.setVisible(accion);
        accesoR2.setVisible(accion);
    }
    
    public void recibir_informacion(List<Organizador> datos){
        orga = datos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Drive = new javax.swing.JLabel();
        accesoR2 = new javax.swing.JLabel();
        accesoR3 = new javax.swing.JLabel();
        accesoR4 = new javax.swing.JLabel();
        nameLBL4 = new javax.swing.JLabel();
        Tag1 = new javax.swing.JLabel();
        Tag2 = new javax.swing.JLabel();
        Tag3 = new javax.swing.JLabel();
        Tag4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(53, 92, 125));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Drive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/calendario.png"))); // NOI18N
        Drive.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(Drive, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 110, 90));

        accesoR2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        accesoR2.setForeground(new java.awt.Color(255, 255, 255));
        accesoR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/calendarioA.png"))); // NOI18N
        accesoR2.setText("Borrar cita");
        accesoR2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accesoR2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accesoR2cambio_paso(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accesoR2retorna_paso(evt);
            }
        });
        add(accesoR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, 30));

        accesoR3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        accesoR3.setForeground(new java.awt.Color(255, 255, 255));
        accesoR3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/calendarioA.png"))); // NOI18N
        accesoR3.setText("Crear nueva cita");
        accesoR3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearEntrada(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accesoR3cambio_paso(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accesoR3retorna_paso(evt);
            }
        });
        add(accesoR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 230, 30));

        accesoR4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        accesoR4.setForeground(new java.awt.Color(255, 255, 255));
        accesoR4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/calendarioc.png"))); // NOI18N
        accesoR4.setText("Consultar cita");
        accesoR4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoR4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accesoR4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accesoR4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accesoR4MouseExited(evt);
            }
        });
        add(accesoR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 30));

        nameLBL4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        nameLBL4.setForeground(new java.awt.Color(255, 255, 255));
        nameLBL4.setText("Nivel de importancia");
        add(nameLBL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        Tag1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Tag1.setForeground(new java.awt.Color(255, 255, 255));
        Tag1.setText("Bajo");
        Tag1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tag1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tag1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tag1cambio_paso(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tag1retorna_paso(evt);
            }
        });
        add(Tag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 180, 20));

        Tag2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Tag2.setForeground(new java.awt.Color(255, 255, 255));
        Tag2.setText("Urgente");
        Tag2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tag2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tag2cambio_paso(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tag2retorna_paso(evt);
            }
        });
        add(Tag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 180, 20));

        Tag3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Tag3.setForeground(new java.awt.Color(255, 255, 255));
        Tag3.setText("Importante");
        Tag3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tag3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tag3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tag3cambio_paso(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tag3retorna_paso(evt);
            }
        });
        add(Tag3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 180, 20));

        Tag4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Tag4.setForeground(new java.awt.Color(255, 255, 255));
        Tag4.setText("Normal");
        Tag4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tag4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tag4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tag4cambio_paso(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tag4retorna_paso(evt);
            }
        });
        add(Tag4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 180, 20));

        jLabel1.setBackground(new java.awt.Color(198, 255, 0));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 20, 20));

        jLabel2.setBackground(new java.awt.Color(244, 67, 54));
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 321, 20, 20));

        jLabel3.setBackground(new java.awt.Color(30, 136, 229));
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 20, 20));

        jLabel4.setBackground(new java.awt.Color(255, 213, 79));
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void accesoR2cambio_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR2cambio_paso
        // TODO add your handling code here:
         Color n = new Color(95,204,156);
        accesoR2.setForeground(n);
    }//GEN-LAST:event_accesoR2cambio_paso

    private void accesoR2retorna_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR2retorna_paso
        // TODO add your handling code here:
        Color n = new Color(240,240,240);
        accesoR2.setForeground(n);
    }//GEN-LAST:event_accesoR2retorna_paso

    private void accesoR3cambio_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR3cambio_paso
        // TODO add your handling code here:
        Color n = new Color(95,204,156);
        accesoR3.setForeground(n);
    }//GEN-LAST:event_accesoR3cambio_paso

    private void accesoR3retorna_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR3retorna_paso

        Color n = new Color(240,240,240);
        accesoR3.setForeground(n);
    }//GEN-LAST:event_accesoR3retorna_paso

    private void accesoR4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR4MouseEntered
        // TODO add your handling code here:
        Color n = new Color(95,204,156);
        accesoR4.setForeground(n);
    }//GEN-LAST:event_accesoR4MouseEntered

    private void accesoR4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR4MouseExited
        // TODO add your handling code here:
        Color n = new Color(240,240,240);
        accesoR4.setForeground(n);
    }//GEN-LAST:event_accesoR4MouseExited

    private void crearEntrada(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearEntrada
        // TODO add your handling code here:
        com.vista.agenda.crearEntrada.CrearEntrada s = new CrearEntrada(vista,userAccedido);
        s.setActivador(true);
        s.setVisible(true);
    }//GEN-LAST:event_crearEntrada

    private void accesoR4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR4MouseClicked
        // TODO add your handling code here:
        vista.paso_informacion_agenda();
        CrearEntrada Actualizar = new CrearEntrada(vista, userAccedido, orga.get(0).getTitulo(), orga.get(0).getDescripcion(), orga.get(0).getFecha(), orga.get(0).getTag(),orga.get(0).getIdorganizador());
        Actualizar.setVisible(true);
    }//GEN-LAST:event_accesoR4MouseClicked

    private void accesoR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoR2MouseClicked
        // TODO add your handling code here:
        vista.paso_informacion_agenda();
        com.vista.opciones.DialogoConfirmacion a = new DialogoConfirmacion(vista, true);
        a.cargaDatos(vista, userAccedido, "Realmente desea eliminar la entrada " + orga.get(0).getTitulo(), orga.get(0).getIdorganizador());
        a.setVisible(true);
    }//GEN-LAST:event_accesoR2MouseClicked

    private void Tag1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Tag1MouseClicked

    private void Tag1cambio_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag1cambio_paso
        // TODO add your handling code here:
        Color n = new Color(95,204,156);
        Tag1.setForeground(n);
    }//GEN-LAST:event_Tag1cambio_paso

    private void Tag1retorna_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag1retorna_paso
        // TODO add your handling code here:
        Color n = new Color(240,240,240);
        Tag1.setForeground(n);
    }//GEN-LAST:event_Tag1retorna_paso

    private void Tag2cambio_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag2cambio_paso
        // TODO add your handling code here:
    }//GEN-LAST:event_Tag2cambio_paso

    private void Tag2retorna_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag2retorna_paso
        // TODO add your handling code here:
    }//GEN-LAST:event_Tag2retorna_paso

    private void Tag3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tag3MouseClicked

    private void Tag3cambio_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag3cambio_paso
        // TODO add your handling code here:
    }//GEN-LAST:event_Tag3cambio_paso

    private void Tag3retorna_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag3retorna_paso
        // TODO add your handling code here:
    }//GEN-LAST:event_Tag3retorna_paso

    private void Tag4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tag4MouseClicked

    private void Tag4cambio_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag4cambio_paso
        // TODO add your handling code here:
    }//GEN-LAST:event_Tag4cambio_paso

    private void Tag4retorna_paso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tag4retorna_paso
        // TODO add your handling code here:
    }//GEN-LAST:event_Tag4retorna_paso


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Drive;
    private javax.swing.JLabel Tag1;
    private javax.swing.JLabel Tag2;
    private javax.swing.JLabel Tag3;
    private javax.swing.JLabel Tag4;
    private javax.swing.JLabel accesoR2;
    private javax.swing.JLabel accesoR3;
    private javax.swing.JLabel accesoR4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nameLBL4;
    // End of variables declaration//GEN-END:variables
}
