/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista.agenda;

import com.controlador.LogicaOrganizador;
import com.modelo.Organizador;
import com.modelo.Usuarios;
import com.vista.Index;
import com.vista.agenda.crearEntrada.CrearEntrada;
import com.vista.opciones.DialogoConfirmacion;
import com.vista.opciones.RespuestaModal;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Camilo
 */
public class panelCitas extends javax.swing.JPanel implements MouseListener{
    private ListadoCitas ventana;
    /**
     * Creates new form panelCitas
     */
    public panelCitas() {
        initComponents();
    }

    public panelCitas(ListadoCitas a, Organizador e, Usuarios user , Index view) {
        initComponents();
        titulo1.setText(e.getTitulo());
        ventana = a;
        ConsultarTag(e.getTag());
        //Btton.addMouseListener(this);
        
        Btton1.addMouseListener(new MouseAdapter() {
            @Override
                public void mouseClicked(MouseEvent s) {
                    com.vista.opciones.DialogoConfirmacion a = new DialogoConfirmacion(view, true);
                    a.cargaDatos(view, user, "Realmente desea eliminar la entrada " + e.getTitulo(), e.getIdorganizador());
                    a.setVisible(true);
                    boolean respuestaModal = a.getResponse();

                    if(respuestaModal){
                        LogicaOrganizador log = new LogicaOrganizador();
                        view.desactualizaAgenda();
                        log.eliminarCita(e.getIdorganizador());
                        com.vista.opciones.RespuestaModal r = new RespuestaModal(view, true);
                        String texto = "<html><body>Se ha eliminado la<br>entrada con exito.<br></body></html>";
                        r.cargaDatos("Atención", texto, "exito");
                        r.setVisible(true);
                    }
                }
        });
        Btton.addMouseListener(new MouseAdapter() {
            @Override
                public void mouseClicked(MouseEvent s) {
                    CrearEntrada actualizar = new CrearEntrada(view, user, e.getTitulo(), e.getDescripcion(), e.getFecha(), e.getTag(), e.getIdorganizador());
                    actualizar.setVisible(true);
                    System.out.println("Yay you clicked me " + e.getDescripcion());
                }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fecha = new javax.swing.JLabel();
        tag = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        Btton = new javax.swing.JLabel();
        Btton1 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        fecha.setText("Fecha");
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 26, 130, 28));

        tag.setOpaque(true);
        add(tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 25, 28));

        label1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        label1.setText("Nivel de importancia");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 135, 28));

        Btton.setBackground(new java.awt.Color(255, 255, 255));
        Btton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Btton.setForeground(new java.awt.Color(51, 102, 255));
        Btton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/view.png"))); // NOI18N
        Btton.setLabelFor(Btton);
        Btton.setText("Detalles");
        Btton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btton.setOpaque(true);
        Btton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BttonMouseExited(evt);
            }
        });
        add(Btton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 95, 40));

        Btton1.setBackground(new java.awt.Color(255, 255, 255));
        Btton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Btton1.setForeground(new java.awt.Color(255, 102, 102));
        Btton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/metaforas/garbage.png"))); // NOI18N
        Btton1.setText("Borrar cita");
        Btton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btton1.setOpaque(true);
        Btton1.setPreferredSize(new java.awt.Dimension(68, 20));
        Btton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btton1MouseExited(evt);
            }
        });
        add(Btton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 100, 40));

        titulo1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        titulo1.setText("Titulo");
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 26, 310, 28));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        Color n = new Color(95,204,156);
        this.setForeground(n);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        Color n = new Color(240,240,240);
        this.setForeground(n);
    }//GEN-LAST:event_formMouseExited

    private void BttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BttonMouseEntered
        // TODO add your handling code here:
        Color n = new Color(95,204,156);
        Btton.setBackground(n);
    }//GEN-LAST:event_BttonMouseEntered

    private void BttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BttonMouseExited
        Color n = new Color(255,255,255);
        Btton.setBackground(n);
    }//GEN-LAST:event_BttonMouseExited

    private void Btton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btton1MouseEntered
        // TODO add your handling code here:
        Color n = new Color(95,204,156);
        Btton1.setBackground(n);
    }//GEN-LAST:event_Btton1MouseEntered

    private void Btton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btton1MouseExited
        Color n = new Color(255,255,255);
        Btton1.setBackground(n);
    }//GEN-LAST:event_Btton1MouseExited

    public void setTextFecha(String te){
        fecha.setText(te);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btton;
    private javax.swing.JLabel Btton1;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel tag;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables

    private void ConsultarTag(String tag) {
        switch(tag){
            case "Urgente":
                this.tag.setBackground(new Color(244,67,54));
                break;
            case "Importante":
                this.tag.setBackground(new Color(30,136,229));
                break;
            case "Normal":
                this.tag.setBackground(new Color(255,213,79));
                break;
            case "Baja":
                this.tag.setBackground(new Color(198,255,0));
                break;
        }
    }
    
    public JLabel botonDetalles(){
        return Btton;
    }
    
    public void setDetalles(JLabel text){
        
    }
    
    public JLabel botonBorrar(){
        return Btton1;
    }


    @Override
    public void mouseClicked(MouseEvent e) {
        if(e.getSource().equals(Btton)){
            JOptionPane.showMessageDialog(ventana, "Se presiono click en " + Btton);
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
